#!/bin/zsh

alias du="du -hcs"
alias df="df -h"

alias ls="ls --color=auto"
alias la="ls --color=always -a"
alias ll="ls --color=always -l"
alias lla="ls --color=always -la"
alias lal="ls --color=always -la"

alias mplayer="mplayer -cache 5000"

alias rm='rm -i'
