#! /bin/zsh
#
# vi-mode colour changing
#   http://www.zsh.org/mla/users/2006/msg01196.html

setopt prompt_subst
autoload colors
colors

rst="%{%b%s%u$reset_color%}"
bgc="%{%(?.$rst.%S)%}"

function rprompt {
    local color1 color2 leftBracket rightBracket
    color1="%{$fg[$2]%}"
    color2="%{$4$fg[$3]%}"
    leftBracket=$color1${1[1]}
    rightBracket=$color1${1[2]}
    RPROMPT='$(get_git_prompt_info)'"$rst$leftBracket$color2%B%~%b$rightBracket$rst"
}

function lprompt {
    setopt prompt_subst

    # let's load colors into our environment, then set them
    autoload colors

    if [[ "$terminfo[colors]" -gt 8 ]]; then
        colors
    fi

    for COLOR in RED GREEN YELLOW BLUE WHITE BLACK; do
        eval PR_$COLOR='%{$fg_no_bold[${(L)COLOR}]%}'
        eval PR_BOLD_$COLOR='%{$fg_bold[${(L)COLOR}]%}'
    done

    local color1 color2 rightBracket leftBracket white
    color1="%{%b$fg[$2]%}"
    color2="%{$4$fg[$3]%}"
    white="%{%b$fg[white]%}"
    leftBracket=$color1${1[1]}
    rightBracket=$color1${1[2]}

    PDIR="$leftBracket$color2%n$white@$color2%m$rightBracket "

    # Finally, let's set the prompt
    #
    # Finally, let's set the prompt
    PROMPT="${PR_BOLD_RED}<${PR_RED}<${PR_BOLD_BLACK}<\
${PR_BOLD_WHITE} ${PDIR} ${PR_RED}!${PR_BOLD_WHITE}%h${PR_BOLD_RED} \
%(?.. E:%?)${PR_BOLD_BLUE}${PR_SCREEN}${PR_JOBS}${PR_GIT}${PR_BATTERY}\
${PR_BOLD_WHITE}${VIMODE}
${PR_BOLD_BLACK}>${PR_GREEN}>${PR_BOLD_GREEN}>\
%{${reset_color}%} "
}

#If the user is root
if [ $UID -eq 0 ]; then
    PROMPT="$bgc%{%B$fg[yellow]%}[%{$fg[red]%}%n %m%{$fg[yellow]%}]$rst "
    RPROMPT="$rst%{$fg[red]%}(%B%{$fg[red]%}%~%b%{$fg[red]%})$rst "

#If a normal user
else
    case $HOST in
        smarties) # In SMARTIES computer
            lprompt '[]' bold green
            rprompt '()' yellow white
            ;;
        rizzo) # In rizzo computer
            lprompt '[]' bold green
            rprompt '()' yellow white
            ;;
        fozzie) # In rizzo computer
            lprompt '[]' bold green
            rprompt '()' yellow white
            ;;
        camilla) # In SMARTIES computer
            lprompt '[]' bold yellow
            rprompt '()' yellow white
            ;;
        *) # In any other computer 
            lprompt '[]' bold blue
            rprompt '()' yellow white
            ;;
    esac
fi

#Variables no longer needed
unset rst bgc
