#! /bin/zsh
#
# vi-mode colour changing
#   http://www.zsh.org/mla/users/2006/msg01196.html

setopt prompt_subst
autoload colors
colors

rst="%{%b%s%u$reset_color%}"
bgc="%{%(?.$rst.%S)%}"

function rprompt {
    local color1 color2 leftBracket rightBracket
    color1="%{$fg[$2]%}"
    color2="%{$4$fg[$3]%}"
    leftBracket=$color1${1[1]}
    rightBracket=$color1${1[2]}
    RPROMPT='$(get_git_prompt_info)'"$rst$leftBracket$color2%B%~%b$rightBracket$rst"
}

function lprompt {
    local color1 color2 rightBracket leftBracket white
    color1="%{%b$fg[$2]%}"
    color2="%{$4$fg[$3]%}"
    white="%{%b$fg[white]%}"
    leftBracket=$color1${1[1]}
    rightBracket=$color1${1[2]}

    PROMPT="$leftBracket$color2%n$white@$color2%m$rightBracket "
}

#If the user is root
if [ $UID -eq 0 ]; then
    PROMPT="$bgc%{%B$fg[yellow]%}[%{$fg[red]%}%n %m%{$fg[yellow]%}]$rst "
    RPROMPT="$rst%{$fg[red]%}(%B%{$fg[red]%}%~%b%{$fg[red]%})$rst "

#If a normal user
else
    case $HOST in
        smarties) # In SMARTIES computer
            lprompt '[]' bold green
            rprompt '()' yellow white
            ;;
        rizzo) # In rizzo computer
            lprompt '[]' bold green
            rprompt '()' yellow white
            ;;
        fozzie) # In rizzo computer
            lprompt '[]' bold green
            rprompt '()' yellow white
            ;;
        camilla) # In SMARTIES computer
            lprompt '[]' bold yellow
            rprompt '()' yellow white
            ;;
        *) # In any other computer 
            lprompt '[]' bold blue
            rprompt '()' yellow white
            ;;
    esac
fi

#Variables no longer needed
unset rst bgc
